# Generated by Django 3.2.9 on 2021-11-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='databse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('UserName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
